=== mtmse/mtm-integration/schemas/statistics-loans-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
		"offset": {
		    "type": "integer",
		    "description": "Offset of the first book in the retrived list."
		},
		"limit": {
		    "type": "integer",
		    "description": "Maximum number of books in the retrived list."
		},
		"total": {
		    "type": "integer",
		    "description": "Total number of books (matching filters, if provided)."
		},
		"registeredAfter": {
		    "type": "string",
		    "description": "Start date limit used in query"
		},
		"registeredBefore": {
		    "type": "string",
		    "description": "End date limit used in query"
		},
        "loanedBook": {
	      	"type": "array",
	      	"description": "A list of books.",
	      	"items": {
	      		"properties":{
                    "sumLoans": {
                        "type": "number",
                        "description": "The number of loans registered for this book during the given time window (between 'registeredBefore' ande 'registeredAfter')."

                    },
		            "book": {
			            "type":"object",
			            "description": "A single book.",
			            "properties": {
			               "mediaNr": {
			                   "type": "string",
			                   "description": "MTM media specific identifier."
			               },
			               "format": {
			                   "type": "string",
			                   "description": "MTM distributable media formats.",
			                   "enum": ["DAISY_202", "PEF", "TEXTVIEW", "TKN", "DTB"]
			               },
			               "fileset": {
			                  "type": "object",
			                   "description": "Information about the actual files containing the literary work.",
			                   "required": ["totalSize"],
			                   "properties": {
			                      "totalSize": {
			                          "type": "number",
			                          "description": "The fileset size in bytes."
			                       }
			                   }
			               },
			               "metadata": {
					            "type": "object",
					            "description": "Meta data describing the book source of the media.",
					            "required": ["title", "author", "language"],
					            "properties": {
					                "title": {
					                    "type": "string"
					                },
					                "sabCode": {
			                    		"type": "string",
			                    		"description": "MTMs classification of the book type."
			                		},
					                "author": {
					                    "type": "array",
					                    "items": {
					                        "type": "string",
					                        "description": "Full name of author."
					                    }
					                },
					                "isbn": {
					                    "type": "string",
					                    "description": "International Standard Book Number of the source material. Missing ISBN is returned as an empty string."
					                },
					                "coverImageUrl": {
					                    "type": "string"
					                },
					                "language": {
					                    "type": "array",
					                    "items": {
					                        "type": "string",
					                        "description": "Langauge(s) used in the book. Language codes according to ISO 639-1, see http://www.loc.gov/standards/iso639-2/php/code_list.php"
					                    }
					                },
					                "narrator": {
					                    "type": "array",
					                    "items": {
					                        "type": "string",
					                        "description": "The names of persons reading the book."
					                    }
					                },
					                "translator": {
					                    "type": "array",
					                    "items": {
					                        "type": "string",
					                        "description": "The names of book translators."
					                    }
					                },
					                "source": {
					                    "type": "object",
					                    "description": "Source publishing information",
					                    "required": ["yearPublished", "publisher"],
					                     "properties": {
					                         "yearPublished": {
					                             "type": "integer",
					                             "description": "The year the book was published"
					                         },
					                         "publisher": {
					                             "type": "string",
					                             "description": "The name of the source publisher of the media."
					                         }
					                     }
					                },
					                "publisher": {
					                    "type": "string",
					                    "description": "The name of the publisher of the media."
					                },
					                "published": {
					                    "type": "string",
					                    "description": "The date when the media was made distributable through this service. Date according ISO 8601 without a time part, see https://www.w3.org/TR/NOTE-datetime"
					                }
					            }
					        },
					        "production": {
	                  		  "type": "object",
	                          "description": "Notifications related to the author/authors",
	                          "required": ["reimbursementEligible"],
	                          "properties": {
	                      	    "reimbursementEligible": {
	                               "type": "boolean",
	                               "description": "If a swedish author is eligble for reimbursement for production of audio book"
	                             }
	                          }
	                        } 
			            }
			        }
			    }

	      	}
    	}

    }
}

=== mtmse/mtm-integration/examples/statistics-loans-example.json
{
  "offset": 0,
  "total": 3,
  "limit": 3,
  "registeredAfter": "2016-05-21T00:00:00+02:00",
  "registeredBefore": "2016-06-23T00:00:00+02:00",
  "loanedBook": [
    {
      "sumLoans": 2,
      "book": {
        "mediaNr": "C16626",
        "format": "DAISY_202",
        "fileset": {
          "totalSize": 0
        },
        "metadata": {
          "title": "Bläckfiskresan",
          "author": [
            "Marie Oskarsson"
          ],
          "isbn": "",
          "coverImageUrl": "http://legimus.se/app/covers/max50x100/C16626.png",
          "language": [
            "sv"
          ],
          "narrator": [
            "Bert Kolker"
          ],
          "source": {
            "publisher": "R&S",
            "yearPublished": 2001
          },
          "published": "2015-09-22",
          "publisher": "TPB"
        },
        "production": {
          "reimbursementEligible": true
        }
      }
    },
    {
      "sumLoans": 1,
      "book": {
        "mediaNr": "CA26588",
        "format": "DAISY_202",
        "fileset": {
          "totalSize": 0
        },
        "metadata": {
          "title": "Nödåret",
          "author": [
            "Aki Ollikainen"
          ],
          "isbn": "978-91-7461-499-2",
          "coverImageUrl": "http://legimus.se/app/covers/max50x100/CA26588.png",
          "language": [
            "sv"
          ],
          "narrator": [
            "Anna Godenius"
          ],
          "translator": [
            "Ann-Christine Relander"
          ],
          "source": {
            "publisher": "N/A",
            "yearPublished": 2016
          },
          "published": "2016-03-07",
          "publisher": "MTM"
        },
        "production": {
          "reimbursementEligible": false
        }
      }
    },
    {
      "sumLoans": 1,
      "book": {
        "mediaNr": "P15242",
        "format": "PEF",
        "fileset": {
          "totalSize": 0
        },
        "metadata": {
          "title": "Barn av sin stad",
          "author": [
            "Per Anders Fogelström"
          ],
          "isbn": "",
          "coverImageUrl": "http://legimus.se/app/covers/max50x100/P15242.png",
          "language": [
            "sv"
          ],
          "source": {
            "publisher": "LL-förl.",
            "yearPublished": 1997
          },
          "published": "2015-03-04",
          "publisher": "TPB"
        },
        "production": {
          "reimbursementEligible": true
        }
      }
    }
  ]
}
